### ISSUE TITLE
pod trunk delete *** 2.2.0 NOT WORK

### ISSUE THREAD

**Issue by huangminlinux** [CocoaPods/trunk.cocoapods.org#213] opened 2016-11-24 17:09 UTC
>pod trunk delete *** 2.2.0 
> y

> [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by Tang8330** [comment] 2016-11-30 02:00
+1

**Comment by orta** [comment] 2016-11-30 06:45
Closing as dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/211

**Closed by orta** 2016-11-30 06:45 UTC
