### ISSUE TITLE
[!] {"name"=>["is already taken"]} after deleting pod

### ISSUE THREAD

**Issue by harquail** [CocoaPods/trunk.cocoapods.org#184] opened 2016-08-10 14:34 UTC
What I'm trying to accomplish: remove old version of our pod, named "YieldMo" currently at 0.0.1.  Upload new specs for current versions, change name to "Yieldmo"

What I did: 
pod trunk deprecate YieldMo 0.0.1
pod trunk delete YieldMo 0.0.1
Trying to pod trunk push the new spec gives me this error:

Validating podspec
 -> Yieldmo (3.0.3)

[!] {"name"=>["is already taken"]}

**Comment by segiddins** [comment] 2016-08-10 14:39
You can't change the case of a pods name.

**Comment by harquail** [comment] 2016-08-10 14:44
ok — not even by deleting the existing pod?

**Comment by orta** [comment] 2016-08-10 15:37
Aye, you're welcome to take a look at adding that - it's just not been done yet ( closing as a dupe of #155 )

**Closed by orta** 2016-08-10 15:37 UTC

**Comment by harquail** [comment] 2016-08-10 15:53
ok, thanks — we'll work around by using a different name
