### ISSUE TITLE
Unverifiable domain

### ISSUE THREAD

**Issue by jeffreyjackson** [CocoaPods/trunk.cocoapods.org#142] opened 2015-07-30 14:39 UTC
I would like to begin using trunk but I'm receiving an error stating that my email is unverifiable.  What do I do?

**Comment by gcox** [comment] 2015-08-07 20:09
@jeffreyjackson If you didn't put quotes around your email address, do so.  I ran into this issue and that was the cause of this in my case.

**Comment by kylef** [comment] 2015-08-08 10:12
@jeffreyjackson If you're using the `jeffreyclarkejackson.com` domain, it seems that it is invalid.

```
 $ host jeffreyclarkejackson.com | grep mail
jeffreyclarkejackson.com mail is handled by 0 mail.jeffreyclarkejackson.com.
```

```
$ host mail.jeffreyclarkejackson.com
Host mail.jeffreyclarkejackson.com not found: 3(NXDOMAIN)
```

**Comment by jeffreyjackson** [comment] 2015-08-10 03:14
kyle, i was looking to use autolean.com

**Comment by kylef** [comment] 2015-10-18 06:48
This slipped by unhanded.

@jeffreyjackson is this still a problem?

**Comment by Imperiopolis** [comment] 2016-03-11 01:45
I've lately started seeing this issue against my domain. The problem domain is `trappdesign.net` and a host lookup against it does return a valid MX record. Any help would be greatly appreciated as I no longer have a registered machine and thus can't update my pods :(

```
host trappdesign.net                                                                                                                                                                                                         master 
trappdesign.net is an alias for fsstats.dnsalias.net.
fsstats.dnsalias.net has address 73.71.204.152
fsstats.dnsalias.net mail is handled by 10 aspmx.l.google.com.
```

**Comment by orta** [comment] 2016-03-11 01:47
I can't find anything in our emailer going to that domain, can you give me an email address?

**Comment by Imperiopolis** [comment] 2016-03-11 02:03
Hey @orta sorry false alarm, this was a problem in my DNS records and everything is working fine now.

**Comment by orta** [comment] 2016-03-11 02:19
Cool, I'm gonna close this out, as we've not had a response in a while.

**Closed by orta** 2016-03-11 02:19 UTC

**Comment by cbess** [comment] 2017-02-18 22:43
I'm running into this issue with `quantumquinn.com`
