### ISSUE TITLE
API request to specs/latest redirecting to wrong URL

### ISSUE THREAD

**Issue by gbanfalvikl** [CocoaPods/trunk.cocoapods.org#234] opened 2017-11-02 13:52 UTC
We released a library `KlarnaCheckoutSDK` that we took down and put up again. 

Now, requests to 
`https://trunk.cocoapods.org/api/v1/pods/KlarnaCheckoutSDK/specs/latest` redirect to what is probably the previous version of the spec, and return a 404 with `curl -siL`. 

Could you please update the spec URL? Thanks in advance!

**Comment by orta** [comment] 2017-11-02 13:54
Looks like a dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/233

**Closed by orta** 2017-11-02 13:54 UTC
